### PR TITLE
Switch tutorial order in schedule

### PR DESCRIPTION
**Pull request by cathmmitchell**

### CODE REVIEW

**Comment by cathmmitchell** [comment]
I haven't built locally, just edited schedule.md

**Comment by emiliom** [comment]
Thanks @cathmmitchell. I'll test it locally before merging.

**Comment by emiliom** [comment]
@cathmmitchell I've tested your changes locally. Looks great, but I ended up making a couple of changes (the main one had to with using markdown-style links within the HTML block). Since I have another change to make to the web site right now, I think the overall easiest route is to close this PR without merging, and I'll include your changes in a new PR shortly. I'll go ahead and close it. Thanks again!

**Comment by emiliom** [comment]
Done

**Pull request closed without merging**
